#! python

from rivtlib.report import *  # noqa: F403

""" generate rivt report

Run this Python file to generate a rivt report as an organized assembly of
rivt docs. Copy and rename this file to save custom report settings.

The report file is written to the docs/report/ folder. Where files exist they
are renamed, not overwritten. A flag determines whether the report is assembled
from existing doc files or whether they are regenerted.  (see "report type
and paths" below).

A rivt report treats each rivt file as a subdivision and its folder ss a
division. Default titles for subdivisions and divisions are generated by
stripping the doc or div number from the file or folder name and replacing
underscores with spaces. Default titles may be changed (see "optional rename"
below). """

# ==================================
# report type and paths
# ==================================
rerun = False  # flag for regenerating doc files [True; False]
rvtype = "rstpdf"  # report type [html; rstpdf; texpdf; text]
inipath = "doc/styles"  # path to rivt.ini file
yamlpath = "doc/styles"  # path to rstpdf.yaml file for rstpdf report
texpath = "doc/styles"  # path to texpdf.sty file for texpdf report
csspath = "doc/styles"  # path to style.css file for html report

# ==================================
# page layout
# ==================================
toc = True  # insert table of contents [True; False]
charwidth = "80"  # text doc width [integer]
pagesize = "letter"  # pdf page size [letter, legal, tabloid]
orient = "portrait"  # [portrait, landscape]
header = "<datetime > | Solar Canopy - Larkspur, Ca. | page < page >"
footer = "<datetime > | Solar Canopy - Larkspur, Ca. | page < page >"

# ==================================
# cover and toc
# ==================================
cover_pdf = ""  # insert cover pdf page - overrides other cover settings
toc = True  # insert table of contents [True; False]
report_title = "Solar Canopy Calculations"  # overrides default title
report_subtitle = "Larkspur, Ca."  # second line of default cover
report_author = "rhh"  # third line of default cover
cover_image = "img.png"  # image
cover_title3 = "<datetime>"  # last line of default cover

# ==================================
# include files and optional rename
# ==================================
dv01 = "Codes and Loads"  # override division title in report
dv02 = ""  # use default subdivision title
dv03 = "Foundation"
#  docs to include in report
rv0101 = "Codes"  # override subdivision title in report
rv0102 = ""  # use default subdivision title
rv0201 = "Steel Frame"
rv0202 = "Solar Panels"
rv0301 = "Slab"
rv0302 = "Walls"

genreport()  # noqa: F405
