#! python

from rivtlib.report import *  # noqa: F403

""" generate rivt report

Run this Python file to generate a report. Different report settings can be
saved in copies of this file. Output is written to the docs/report/_subfolder_
where _subfolder_ is the report type. A flag determines whether the report is
assembled from existing doc files or whether rivt files are first rerun (see
"process" below).

In a report each rivt file becomes a subdivision and a folder becomes a
division. Default subdivision and division titles are generated by stripping
the doc number and replacing underscores with spaces in the file or folder
name. The deafaults can be overwritten (see "include and rename" below). """

# ===========================
# report type and paths
# ===========================
rerun = False  # flag for rerunning rivt files [True; False]
rtype = "rstpdf"  # report type [html; rstpdf; texpdf; text]
iniP = "doc/styles"  # path to rivt.ini file
rstyamlP = "doc/styles"  # path to rstpdf.yaml file

# ===========================
# page layout
# ===========================
toc = True  # insert table of contents [True; False]
charwidth = "80"  # text doc width [integer]
pagesize = "letter"  # pdf page size [letter, tabloid]
header = "<datetime > | Solar Canopy - Larkspur, Ca. | page < page >"
footer = "<datetime > | Solar Canopy - Larkspur, Ca. | page < page >"

# ===========================
# cover and toc
# ===========================
cover_pdf = ""  # insert cover (overrides other cover settings)
toc = True  # insert table of contents
report_title = "Solar Canopy Calculations"  # overrides default titile
report_subtitle = "Larkspur, Ca."  # second line of default cover
report_author = "rhh"  # third line of default cover
cover_image = "img.png"  # image
cover_title3 = "<datetime>"  # last line of default cover

# ===========================
# include and rename
# ===========================

dv01 = "Codes and Loads"  # rename a division (folder)
rv0101 = "Codes"  # rename a subdivision (file)
rv0102 = ""  # use default name

dv02 = "Frame"
rv0201 = "Steel Frame"
rv0202 = "Solar Panels"

dv03 = "Foundation"
rv0301 = "Slab"
rv0302 = "Walls"

genreport()  # noqa: F405
