#! python

from rivtlib.report import *  # noqa: F403

""" generate rivt report

Sample report config file. Run this Python file to generate a rivt report. Copy
and rename the file to save custom report settings.

The report file is written to the folder rivtdocs/report/. Duplicate report
files are incremented, not overwritten. A flag determines whether the report is
assembled from existing doc files or whether they are regenerated prior to
assembly. (see "report type and paths" below). If a doc file is specified and
not found it is silently skipped.

A rivt report organizes folders as divisions and rivt docs (files) as
subdivisions. rivt doc numbers reflect this structure. Default titles for
subdivisions and divisions are generated by stripping the doc or div number
from the file or folder name and replacing underscores with spaces. The default
titles may be changed (see "optional rename" below). """

# ==================================
# report type and paths
# ==================================
reptype = "rstpdf"  # report type [html; rstpdf; texpdf; text]
reptitle = ""

# ==================================
# include files and optional rename
# ==================================

# divisions to include in report
dv01 = "Codes and Loads"  # override division title
dv02 = ""  # use default division title
dv03 = "Foundation"

#  docs to include in report
rv0101 = "Codes"  # override subdivision title in report
rv0102 = ""  # use default subdivision title
rv0201 = "Steel Frame"
rv0202 = "Solar Panels"
rv0301 = "Slab"
rv0302 = "Walls"

genreport()  # noqa: F405
